# Generated by Django 2.0.6 on 2018-07-09 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('net', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=999),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
