# Generated by Django 2.0.6 on 2018-07-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180709_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(default='SWKD-00000', max_length=10),
        ),
    ]
